######################################################################
# Automatically generated by qmake (1.07a) Mon Jun 6 16:32:05 2016
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += tictac.h
SOURCES += main.cpp tictac.cpp
