######################################################################
# Automatically generated by qmake (1.07a) Wed Sep 15 10:18:57 2004
######################################################################

TEMPLATE = app
DEPENDPATH += crow
INCLUDEPATH += . crow

# Input
HEADERS += calibrate.h 
SOURCES += calibrate.cpp main.cpp 
