#############################################################################
# Qt Makefile - doc
#############################################################################
# $Id: qt/Makefile   3.3.3   edited May 27 2003 $

showfiles showsources:
	@echo *.doc

clean:
	-rm -f *~ *% #*

obj include depend:
