######################################################################
# Automatically generated by qmake (1.07a) Tue Jun 7 01:22:02 2016
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += tictac.h
SOURCES += main.cpp tictac.cpp
